# Generated by Django 5.2.1 on 2025-06-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Статус публикации"
            ),
        ),
    ]
