# Generated by Django 5.2.1 on 2025-06-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
