# Generated by Django 5.2.1 on 2025-06-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category", "description"],
                "permissions": [
                    ("can_unpublish_product", "Can unpublish product"),
                    ("can_publish_product", "Can publish product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
